#!/usr/bin/env node
// scripts/generate-spec.mjs — VEPA4 deterministic spec generator
// Reads live source contracts and produces docs/spec/ artefacts.
// No runtime dependencies — Node built-ins only.
// Usage: node scripts/generate-spec.mjs [--check]

import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url)) + '/..';
const SPEC_DIR = join(ROOT, 'docs', 'spec');
const CHECK_MODE = process.argv.includes('--check');
const HEADER = '<!-- Generated by scripts/generate-spec.mjs; do not edit. -->\n\n';

// ── Helpers ──────────────────────────────────────────────────────────────────

function read(rel) {
  return readFileSync(join(ROOT, rel), 'utf8');
}

function readLines(rel) {
  return read(rel).split('\n');
}

function writeSpec(rel, content) {
  const full = join(SPEC_DIR, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content, 'utf8');
}

function walkDir(dir, filter) {
  const results = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fp = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.dist') continue;
      results.push(...walkDir(fp, filter));
    } else if (!filter || filter(fp)) {
      results.push(fp);
    }
  }
  return results;
}

function relFromSpec(fp) {
  return relative(SPEC_DIR, fp).split(sep).join('/');
}

function relToRoot(fp) {
  return relative(ROOT, fp).split(sep).join('/');
}

function esc(s) {
  return String(s).replace(/\|/g, '\\|');
}

// ── Parse constants.js ───────────────────────────────────────────────────────

function parseConstants() {
  const src = read('src/constants.js');
  const fullSrc = src + '\n' + read('src/physics/lawgroups/mechanicsHelp.js');

  // Extract PARTICLE_STRIDE
  const strideMatch = src.match(/PARTICLE_STRIDE\s*=\s*(\d+)/);
  const PARTICLE_STRIDE = strideMatch ? Number(strideMatch[1]) : 100;

  // Extract DNA_COUNT
  const dnaCountMatch = src.match(/DNA_COUNT\s*=\s*(\d+)/);
  const DNA_COUNT = dnaCountMatch ? Number(dnaCountMatch[1]) : 64;

  // Extract LAW_COUNT
  const lawCountMatch = src.match(/LAW_COUNT\s*=\s*(\d+)/);
  const LAW_COUNT = lawCountMatch ? Number(lawCountMatch[1]) : 136;

  // Extract LAW_INDEXES name→value pairs
  const LAW_INDEXES = {};
  const lawIdxRe = /(\w+):\s*(\d+)/g;
  const lawIdxBlock = src.match(/export const LAW_INDEXES\s*=\s*\{([\s\S]*?)\};/);
  if (lawIdxBlock) {
    let m;
    while ((m = lawIdxRe.exec(lawIdxBlock[1]))) {
      LAW_INDEXES[m[1]] = Number(m[2]);
    }
  }
  const INDEX_TO_NAME = {};
  for (const [name, idx] of Object.entries(LAW_INDEXES)) INDEX_TO_NAME[idx] = name;

  // Extract LAW_CATEGORIES — we need to resolve LAW_INDEXES.X references
  const LAW_CATEGORIES = {};
  const catBlock = src.match(/export const LAW_CATEGORIES\s*=\s*\{([\s\S]*?)\n\};/);
  if (catBlock) {
    const catRe = /(\w+):\s*\{\s*color:\s*'(\w+)',\s*laws:\s*\[([\s\S]*?)\]/g;
    let cm;
    while ((cm = catRe.exec(catBlock[1]))) {
      const catName = cm[1];
      const color = cm[2];
      const lawRefs = cm[3];
      const lawNums = [];
      const refRe = /LAW_INDEXES\.(\w+)/g;
      let rm;
      while ((rm = refRe.exec(lawRefs))) {
        if (LAW_INDEXES[rm[1]] !== undefined) lawNums.push(LAW_INDEXES[rm[1]]);
      }
      LAW_CATEGORIES[catName] = { color, laws: lawNums };
    }
  }

  // Extract LAW_PARAMETERS
  const LAW_PARAMETERS = {};
  const paramBlock = src.match(/export const LAW_PARAMETERS\s*=\s*\{([\s\S]*?)\n\};/);
  if (paramBlock) {
    const paramRe = /\[LAW_INDEXES\.(\w+)\]:\s*\[([^\]]*)\]/g;
    let pm;
    while ((pm = paramRe.exec(paramBlock[1]))) {
      const idx = LAW_INDEXES[pm[1]];
      if (idx !== undefined) {
        LAW_PARAMETERS[idx] = pm[2].split(',').map(s => s.trim().replace(/^['"]|['"]$/g, ''));
      }
    }
  }

  // Extract LAW_HELP_DB
  const LAW_HELP_DB = {};
  const helpBlock = src.match(/export const LAW_HELP_DB\s*=\s*\{([\s\S]*?)\n\};/);
  if (helpBlock) {
    const helpRe = /\[(\d+)\]:\s*\{([^}]*)\}/g;
    let hm;
    while ((hm = helpRe.exec(helpBlock[1]))) {
      const idx = Number(hm[1]);
      const fields = {};
      const tierRe = /(\w+):\s*'([^']*)'/g;
      let tm;
      while ((tm = tierRe.exec(hm[2]))) {
        fields[tm[1].toLowerCase()] = tm[2];
      }
      LAW_HELP_DB[idx] = fields;
    }
  }

  // Extract LAW_HELP_PATCHES (supplemental help)
  const LAW_HELP_PATCHES = {};
  const patchSrc = existsSync(join(ROOT, 'src/state/lawHelpPatches.js')) ? read('src/state/lawHelpPatches.js') : '';
  if (patchSrc) {
    const patchBlock = patchSrc.match(/export const LAW_HELP_PATCHES\s*=\s*\{([\s\S]*?)\n\};/);
    if (patchBlock) {
      const patchRe = /\[(\d+)\]:\s*\{([^}]*)\}/g;
      let pm2;
      while ((pm2 = patchRe.exec(patchBlock[1]))) {
        const idx = Number(pm2[1]);
        const fields = {};
        const tierRe = /(\w+):\s*'([^']*)'/g;
        let tm;
        while ((tm = tierRe.exec(pm2[2]))) {
          fields[tm[1].toLowerCase()] = tm[2];
        }
        LAW_HELP_PATCHES[idx] = fields;
      }
    }
  }

  // Merge help: canonical + patches
  const MERGED_HELP = {};
  for (const idx of Object.keys(LAW_HELP_DB).map(Number)) {
    MERGED_HELP[idx] = { ...LAW_HELP_DB[idx] };
  }
  for (const idx of Object.keys(LAW_HELP_PATCHES).map(Number)) {
    if (!MERGED_HELP[idx]) MERGED_HELP[idx] = {};
    for (const [k, v] of Object.entries(LAW_HELP_PATCHES[idx])) {
      if (!MERGED_HELP[idx][k] || MERGED_HELP[idx][k] === 'MISSING') MERGED_HELP[idx][k] = v;
    }
  }

  // MECHANICS_HELP from mechanicsHelp.js
  const MECHANICS_HELP = {};
  const mechHelpBlock = fullSrc.match(/export const MECHANICS_HELP\s*=\s*\{([\s\S]*?)\n\};/);
  if (mechHelpBlock) {
    const mhRe = /(\w+):\s*\{([^}]*)\}/g;
    let mhm;
    while ((mhm = mhRe.exec(mechHelpBlock[1]))) {
      const name = mhm[1];
      const idx = LAW_INDEXES[name];
      if (idx !== undefined) {
        const fields = {};
        const fRe = /(\w+):\s*'([^']*)'/g;
        let fm;
        while ((fm = fRe.exec(mhm[2]))) {
          fields[fm[1].toLowerCase()] = fm[2];
        }
        MECHANICS_HELP[idx] = fields;
      }
    }
  }

  // Merge MECHANICS_HELP into MERGED_HELP
  for (const [idxStr, fields] of Object.entries(MECHANICS_HELP)) {
    const idx = Number(idxStr);
    if (!MERGED_HELP[idx]) MERGED_HELP[idx] = {};
    for (const [k, v] of Object.entries(fields)) {
      if (!MERGED_HELP[idx][k] || MERGED_HELP[idx][k] === 'MISSING') MERGED_HELP[idx][k] = v;
    }
  }

  return {
    PARTICLE_STRIDE, DNA_COUNT, LAW_COUNT,
    LAW_INDEXES, INDEX_TO_NAME,
    LAW_CATEGORIES, LAW_PARAMETERS, LAW_HELP_DB, LAW_HELP_PATCHES,
    MERGED_HELP, MECHANICS_HELP,
  };
}

// ── Source scanning ──────────────────────────────────────────────────────────

function classifyFile(fp) {
  const r = relative(ROOT, fp);
  if (r.startsWith('src/physics/') || r.startsWith('src/spawn/') || r.startsWith('src/worker/')) return 'simulation';
  if (r.startsWith('src/ui/')) return 'ui';
  if (r.startsWith('src/state/') || r.startsWith('src/dna/')) return 'state';
  if (r.startsWith('tests/')) return 'testing';
  if (r.startsWith('bench/')) return 'benchmark';
  if (r.startsWith('docs/')) return 'documentation';
  if (r.startsWith('audit-suite/')) return 'documentation';
  if (r.startsWith('exports/')) return 'documentation';
  if (r === 'package.json' || r === 'package-lock.json' || r === 'vite.config.js' || r === 'vitest.config.js' || r === 'vercel.json' || r === 'index.html' || r === 'style.css') return 'repository';
  if (r.startsWith('scripts/')) return 'runtime';
  return 'application';
}

function scanSourceFiles(LAW_INDEXES) {
  const files = walkDir(ROOT, fp => {
    const ext = fp.split('.').pop();
    return ['js', 'mjs', 'json', 'html', 'css'].includes(ext) && !fp.includes('node_modules') && !fp.includes('.dist');
  });

  const modules = files.map(fp => {
    const rel = relToRoot(fp);
    let content = '';
    try { content = readFileSync(fp, 'utf8'); } catch { return null; }
    const lines = content.split('\n');
    const lineCount = lines.length;

    // Count exports
    const exportMatches = content.match(/\bexport\s+(default\s+)?(function|class|const|let|var|async)\s+\w+/g) || [];
    const exportDefault = content.match(/\bexport\s+default\b/g) || [];
    const exportNames = content.match(/\bexport\s+\{([^}]+)\}/g) || [];
    const exportCount = exportMatches.length + exportDefault.length + exportNames.length;

    // Count imports
    const importMatches = content.match(/\bimport\s+/g) || [];
    const importCount = importMatches.length;

    // Law references
    const lawRefs = new Set();
    for (const [name, idx] of Object.entries(LAW_INDEXES)) {
      if (content.includes(name)) lawRefs.add(idx);
    }

    const area = classifyFile(fp);

    return {
      rel, area, lineCount, exportCount, importCount,
      lawRefCount: lawRefs.size,
      lawRefs: [...lawRefs].sort((a, b) => a - b),
      content,
    };
  }).filter(Boolean);

  return modules;
}

function scanTestFiles(LAW_INDEXES) {
  const testFiles = walkDir(ROOT, fp => fp.endsWith('.test.js') || fp.endsWith('.spec.js'));
  const results = [];

  for (const fp of testFiles) {
    const rel = relToRoot(fp);
    let content = '';
    try { content = readFileSync(fp, 'utf8'); } catch { continue; }
    const lawRefs = new Set();
    for (const [name, idx] of Object.entries(LAW_INDEXES)) {
      if (content.includes(name)) lawRefs.add(idx);
    }
    results.push({ rel, lawRefs: [...lawRefs] });
  }

  return results;
}

function scanAuditFiles(LAW_INDEXES) {
  const auditDir = join(ROOT, 'docs', 'audit');
  const auditFiles = walkDir(auditDir, fp => fp.endsWith('.md'));
  const results = [];

  for (const fp of auditFiles) {
    const rel = relToRoot(fp);
    let content = '';
    try { content = readFileSync(fp, 'utf8'); } catch { continue; }
    const lawRefs = new Set();
    for (const [name, idx] of Object.entries(LAW_INDEXES)) {
      if (content.includes(name)) lawRefs.add(idx);
    }
    results.push({ rel, lawRefs: [...lawRefs] });
  }

  return results;
}

// ── Find implementation evidence for each law ────────────────────────────────

function findImplementations(lawName, lawIdx, modules) {
  const impls = [];
  // Look in lawgroup files and laws.js
  for (const m of modules) {
    if (m.area !== 'simulation') continue;
    // Check for apply<LawName> or similar function references
    const patterns = [
      new RegExp(`\\bapply${lawName}\\b`, 'i'),
      new RegExp(`\\b${lawName}\\b`, 'i'),
    ];
    for (const pat of patterns) {
      if (pat.test(m.content)) {
        if (!impls.includes(m.rel)) impls.push(m.rel);
        break;
      }
    }
  }
  return impls;
}

// ── Status determination ─────────────────────────────────────────────────────

function determineStatus(lawIdx, lawName, impls, gateRefs) {
  if (impls.length > 0) return 'wired';
  if (gateRefs > 0) return 'gated-no-export-evidence';
  return 'metadata-only';
}

// ── Help source determination ────────────────────────────────────────────────

function helpSource(lawIdx, constants) {
  const inDb = constants.LAW_HELP_DB[lawIdx] !== undefined;
  const inPatches = constants.LAW_HELP_PATCHES[lawIdx] !== undefined;
  const inMech = constants.MECHANICS_HELP[lawIdx] !== undefined;
  if (inDb && inPatches) return 'LAW_HELP_DB+LAW_HELP_PATCHES';
  if (inDb) return 'LAW_HELP_DB';
  if (inPatches) return 'LAW_HELP_PATCHES';
  if (inMech) return 'MECHANICS_HELP';
  return 'NONE';
}

// ── Generate architecture branch ─────────────────────────────────────────────

function genArchitecture(modules, constants) {
  const areas = {};
  for (const m of modules) {
    if (!areas[m.area]) areas[m.area] = { files: 0, exports: 0, imports: 0, lawRefs: 0 };
    areas[m.area].files++;
    areas[m.area].exports += m.exportCount;
    areas[m.area].imports += m.importCount;
    areas[m.area].lawRefs += m.lawRefCount;
  }

  // general.md
  writeSpec('architecture/general.md', HEADER + `# Architecture: General

VEPA4 is a browser simulation with a main-thread orchestrator, optional physics worker, flat particle memory, stateless lawgroup primitives, a spatial-neighbor path, and a programmatic UI. The source is modular JavaScript ESM and Vite packages the browser entrypoint.

## Responsibilities

| Boundary | Responsibility | Evidence |
| --- | --- | --- |
| Main thread | Bootstrap, UI, rendering, worker bridge and world orchestration | [src/main.js](${relToRoot('src/main.js')}) |
| Worker | Initialize/configure buffers and execute serialized physics ticks | [src/worker/physics.worker.js](${relToRoot('src/worker/physics.worker.js')}) |
| Solver | Build neighbors, gate laws, integrate bounded motion and run lifecycle | [src/physics/solver.js](${relToRoot('src/physics/solver.js')}) |
| State | Own buffers, masks, runtime parameters, persistence and subsystem state | [src/state](${relToRoot('src/state')}) |
| UI | Create controls against DOM, EventBus and runtime contracts | [src/ui](${relToRoot('src/ui')}) |
| Renderer | Project live particle state into canvas/Pixi output | [src/render](${relToRoot('src/render')}) |

## Current contract

- Particle stride: \`${constants.PARTICLE_STRIDE}\` floats.
- Species DNA count: \`${constants.DNA_COUNT}\`.
- Declared law count: \`${constants.LAW_COUNT}\`.
- Source records scanned: \`${modules.length}\`.

The generated module inventory is the detailed API index. This document describes ownership and execution boundaries rather than reproducing every function.
`);

  // dataflow.md
  writeSpec('architecture/dataflow.md', HEADER + `# Architecture: Dataflow

## Tick dataflow

- UI or orchestrator updates runtime configuration and law state.
- Main thread sends serialized configuration to the worker when worker execution is active.
- Solver reads the particle view and species DNA, builds/reuses neighbors, and applies active law families.
- Stateful field and emergent subsystem passes update their own buffers or registries on cadence.
- Renderer and HUD read the resulting buffer and metrics for the next frame.

Evidence: [src/main.js](${relToRoot('src/main.js')}), [src/worker/physics.worker.js](${relToRoot('src/worker/physics.worker.js')}), and [src/physics/solver.js](${relToRoot('src/physics/solver.js')}).
`);

  // module-boundaries.md
  const areaRows = Object.entries(areas)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([a, v]) => `| ${esc(a.charAt(0).toUpperCase() + a.slice(1))} | ${v.files} | ${v.exports} | ${v.imports} | ${v.lawRefs} |`)
    .join('\n');

  writeSpec('architecture/module-boundaries.md', HEADER + `# Architecture: Module Boundaries

| Area | Files | Exports | Imports | Law references |
| --- | --- | --- | --- | --- |
${areaRows}

## Boundary observations

- The solver imports shared law primitives and category lawgroups, so law records must be reviewed with dispatch evidence.
- The active law mask has a penta word for the full law range, while older prose may describe fewer words.
- The UI reads the canonical help object and overlays supplemental patches at runtime.
- Package lock metadata is checked independently because it can drift from package.json during uncommitted work.
`);

  // runtime/build.md and runtime/worker.md
  writeSpec('architecture/runtime/build.md', HEADER + `# Architecture: Runtime: Build

Vite packages the browser entrypoint. The build target is ESM. The worker is compiled separately with \`worker.format: 'es'\` in vite.config.js. COOP/COEP headers are required for SharedArrayBuffer.
`);
  writeSpec('architecture/runtime/worker.md', HEADER + `# Architecture: Runtime: Worker

The physics worker ([src/worker/physics.worker.js](${relToRoot('src/worker/physics.worker.js')})) receives serialized configuration messages and runs the solver in an isolated thread. The main thread reads the shared particle buffer for rendering.
`);
}

// ── Generate UI branch ───────────────────────────────────────────────────────

function genUI(modules) {
  const uiModules = modules.filter(m => m.area === 'ui');

  writeSpec('ui/general.md', HEADER + `# UI: General

The UI is programmatic DOM code under [src/ui](${relToRoot('src/ui')}). Panels receive EventBus and state references, render controls, wire events, and publish domain actions.

| Surface | Module | Observed responsibility |
| --- | --- | --- |
| Law controls | [src/ui/lawPanel.js](${relToRoot('src/ui/lawPanel.js')}) | Category-grouped toggles, slate Mechanics section and law events |
| World controls | [src/ui/worldPanel.js](${relToRoot('src/ui/worldPanel.js')}) | World parameters, presets and setup |
| Tooltip/help | [src/ui/tooltip.js](${relToRoot('src/ui/tooltip.js')}) | Law lookup, help tiers and toggle affordance |
| Persistence | [src/ui/savePanel.js](${relToRoot('src/ui/savePanel.js')}) | Save, restore, compare, undo and redo |
| Analytics | eco, group, DNA, intel and narrative panels | Inspection surfaces for emergent state |

Functional UI evidence is separated from appearance evidence so interaction regressions and visual regressions remain independently reviewable.
`);

  writeSpec('ui/appearance.md', HEADER + `# UI: Appearance

Visual styling uses a neon-noir lab aesthetic: deep-space radial gradient backdrop, CRT scanline overlay, and color-coded category law toggles. Toolbar buttons pulse and glow on hover/active states. The drawer slides with a transform+visibility transition.
`);

  writeSpec('ui/function.md', HEADER + `# UI: Function

Panels are wired through EventBus subscriptions. Law toggles emit \`toggle:law\` events. World parameter changes emit \`world:update\`. Persistence operations use \`save:*\` and \`load:*\` event families. The HUD updates on cadence-gated tick counts.
`);

  writeSpec('ui/surfaces.md', HEADER + `# UI: Surfaces

| Surface | File | DOM target |
| --- | --- | --- |
${uiModules.map(m => `| ${esc(dirname(m.rel).split('/').pop())} | [${m.rel}](${relToRoot(m.rel)}) | programmatic |`).join('\n')}
`);
}

// ── Generate sim branch ──────────────────────────────────────────────────────

function genSim(constants, modules) {
  writeSpec('sim/general.md', HEADER + `# Simulation: General

VEPA4 advances a particle world through neighbor discovery, gated pairwise laws, gated per-particle laws, bounded integration, lifecycle, and cadence-based subsystem passes.

| Branch | Specification |
| --- | --- |
| Solver | [sim/solver.md](solver.md) |
| Fields and medium | [sim/fields.md](fields.md) |
| Lifecycle and emergence | [sim/lifecycle.md](lifecycle.md) |
| Similar concepts | [sim/concepts.md](concepts.md) |
| Law roster | [laws/index.md](../laws/index.md) |

The runtime law count and category roster are derived from constants, not from this prose.
`);

  writeSpec('sim/solver.md', HEADER + `# Simulation: Solver

The solver ([src/physics/solver.js](${relToRoot('src/physics/solver.js')})) runs the per-tick physics loop:

1. Build or reuse the neighbor list via the spatial grid.
2. Apply active pairwise law families (gravity, drag, collision, bonds, EM, etc.).
3. Apply active per-particle law families (lifecycle, thermodynamics, metaphysics, quantum).
4. Integrate position and velocity with bounds clamping.
5. Run lifecycle and cadence-based subsystem passes.

The solver is law-gated: with zero laws active, no movement, interaction, or state change occurs.
`);

  writeSpec('sim/fields.md', HEADER + `# Simulation: Fields and Medium

The field system ([src/physics/fields.js](${relToRoot('src/physics/fields.js')})) provides vector fields, scalar fields, walls, gravity wells, and portals. Fields are read by the solver as external forces on particles within their spatial extent.
`);

  writeSpec('sim/lifecycle.md', HEADER + `# Simulation: Lifecycle and Emergence

Lifecycle effects include reproduction (REPRO), death (LIFE/SENESCENCE), energy metabolism, aging, and species evolution. Emergent behaviors arise from law synergies — for example, COMMS + LEARN produces adaptive communication, and GRAV + ACCR produces gravitational clustering.
`);

  writeSpec('sim/concepts.md', HEADER + `# Simulation: Similar Concepts

Several law families overlap conceptually. FRICTION vs DRAG: FRICTION is velocity-dependent damping gated by the FRICTION law, while DRAG is the broader kinetic dampening law. INERTIA (DNA 26) vs MASS_INERTIA (law 86): DNA INERTIA scales force response per-particle, while MASS_INERTIA is a category-level physics law.
`);
}

// ── Generate state branch ────────────────────────────────────────────────────

function genState(constants) {
  writeSpec('state/general.md', HEADER + `# State: General

Simulation state is split between flat particle memory, species DNA, law masks, runtime parameters, subsystem state, and persistence adapters.

| State family | Evidence | Contract |
| --- | --- | --- |
| Particle buffer | [src/state/particleBuffer.js](${relToRoot('src/state/particleBuffer.js')}) | Float32Array over SharedArrayBuffer or ArrayBuffer |
| Species DNA | [src/dna/dnaBuffer.js](${relToRoot('src/dna/dnaBuffer.js')}) | Genome buffer separate from per-particle cache |
| Law mask | [src/state/lawState.js](${relToRoot('src/state/lawState.js')}) | Multiple words for law indexes 0-${constants.LAW_COUNT - 1} |
| Runtime configuration | [src/state/runtimeConfig.js](${relToRoot('src/state/runtimeConfig.js')}) | Mutable live configuration passed into execution |
| World persistence | [src/state/worldSave.js](${relToRoot('src/state/worldSave.js')}) | Capture, restore, export, compare and undo |
`);

  writeSpec('state/law-state.md', HEADER + `# State: Law State

The law state uses a bitmask of multiple words to track which of the ${constants.LAW_COUNT} laws are active. Each word covers a contiguous range of law indexes. Toggle operations are atomic per word.

Evidence: [src/state/lawState.js](${relToRoot('src/state/lawState.js')}).
`);

  writeSpec('state/persistence.md', HEADER + `# State: Persistence

World states are captured, restored, compared, and undone via [src/state/worldSave.js](${relToRoot('src/state/worldSave.js')}). Presets are managed by [src/state/presetManager.js](${relToRoot('src/state/presetManager.js')}). Persistence includes particle buffers, DNA, law state, and runtime configuration.
`);

  writeSpec('state/stride.md', HEADER + `# State: Stride

Each particle occupies exactly ${constants.PARTICLE_STRIDE} floats in the flat buffer. Base pointer: \`index * ${constants.PARTICLE_STRIDE}\`. The stride layout covers position, velocity, mass, species ID, DNA cache, energy, lifecycle state, bonds, electrical/thermal state, quantum state, and reserved tail slots.
`);
}

// ── Generate laws branch ─────────────────────────────────────────────────────

function genLaws(constants, modules, testFiles, auditFiles) {
  const { LAW_INDEXES, INDEX_TO_NAME, LAW_CATEGORIES, LAW_PARAMETERS, MERGED_HELP, LAW_HELP_DB, LAW_HELP_PATCHES, MECHANICS_HELP, LAW_COUNT } = constants;

  // Build per-law data
  const lawData = [];
  for (let i = 0; i < LAW_COUNT; i++) {
    const name = INDEX_TO_NAME[i];
    if (!name) continue;

    // Find category
    let category = 'unknown';
    let color = 'GRAY';
    for (const [cat, info] of Object.entries(LAW_CATEGORIES)) {
      if (info.laws.includes(i)) { category = cat; color = info.color; break; }
    }

    // Find implementation evidence
    const impls = [];
    for (const m of modules) {
      if (m.area !== 'simulation') continue;
      const pat = new RegExp(`\\b${name}\\b`);
      if (pat.test(m.content)) impls.push(m.rel);
    }

    // Gate references (solver dispatches)
    const gateRefs = new Set();
    for (const m of modules) {
      if (!m.rel.includes('solver')) continue;
      const pat = new RegExp(`\\b${name}\\b`);
      if (pat.test(m.content)) gateRefs.add(m.rel);
    }

    // Test evidence
    const testRefs = [];
    for (const t of testFiles) {
      if (t.lawRefs.includes(i)) testRefs.push(t.rel);
    }

    // Audit evidence
    const auditRefs = [];
    for (const a of auditFiles) {
      if (a.lawRefs.includes(i)) auditRefs.push(a.rel);
    }

    const status = determineStatus(i, name, impls, gateRefs.size);
    const hSource = helpSource(i, constants);
    const params = LAW_PARAMETERS[i] || [];

    lawData.push({
      idx: i, name, category, color, status,
      impls, gateRefs: gateRefs.size,
      testRefs, auditRefs,
      helpSource: hSource, params,
    });
  }

  // laws/index.md
  const catRows = Object.entries(LAW_CATEGORIES)
    .map(([cat, info]) => {
      const solverWired = lawData.filter(l => l.category === cat && l.gateRefs > 0).length;
      const merged = lawData.filter(l => l.category === cat && MERGED_HELP[l.idx] && Object.keys(MERGED_HELP[l.idx]).length > 0).length;
      return `| ${esc(cat.charAt(0).toUpperCase() + cat.slice(1))} | ${esc(info.color)} | ${info.laws.length} | ${solverWired} | ${merged} |`;
    })
    .join('\n');

  const totalMapped = lawData.length;
  const canonicalHelp = Object.keys(LAW_HELP_DB).length;
  const mergedHelp = lawData.filter(l => MERGED_HELP[l.idx] && Object.keys(MERGED_HELP[l.idx]).length > 0).length;

  writeSpec('laws/index.md', HEADER + `# Laws: Index

The law catalog is generated from LAW_INDEXES, LAW_CATEGORIES and associated metadata in [src/constants.js](${relToRoot('src/constants.js')}). There are \`${totalMapped}\` mapped records across \`${Object.keys(LAW_CATEGORIES).length}\` categories.

## Category coverage

| Category | Color | Count | Solver-wired records | Merged help records |
| --- | --- | --- | --- | --- |
${catRows}

## Contract findings

- Canonical LAW_HELP_DB entries: ${canonicalHelp}/${totalMapped}.
- Merged help entries after supplemental sources: ${mergedHelp}/${totalMapped}.
- Every mapped law has merged help evidence.
- Every category overview links to one generated record per law index.

## Category branches

${Object.keys(LAW_CATEGORIES).map(cat => `- [${esc(cat.charAt(0).toUpperCase() + cat.slice(1))}](categories/${cat}/overview.md)`).join('\n')}
`);

  // Per-category overview
  for (const [cat, info] of Object.entries(LAW_CATEGORIES)) {
    const catLaws = lawData.filter(l => l.category === cat);
    const rows = catLaws.map(l => {
      const pad = String(l.idx).padStart(3, '0');
      return `| ${l.idx} | [${esc(l.name)}](../../${cat}/${pad}_${esc(l.name)}.md) | ${esc(l.status)} | ${esc(l.helpSource)} | ${esc(l.impls.length > 0 ? l.impls[0] : 'not found')} |`;
    }).join('\n');

    writeSpec(`laws/categories/${cat}/overview.md`, HEADER + `# Laws: ${esc(cat.charAt(0).toUpperCase() + cat.slice(1))}

- Color: \`${esc(info.color)}\`
- Mapped count: \`${info.laws.length}\`
- Declared roster: \`${info.laws.join(', ')}\`

| Index | Law | Status | Help | Implementation |
| --- | --- | --- | --- | --- |
${rows}

The category roster is a classification contract. Behavior evidence is in individual records and [traceability/laws.md](../../../traceability/laws.md).
`);
  }

  // Per-law records
  for (const l of lawData) {
    const pad = String(l.idx).padStart(3, '0');
    const help = MERGED_HELP[l.idx] || {};

    const testLinks = l.testRefs.length > 0
      ? l.testRefs.map(r => `[${r}](${relToRoot(r)})`).join(', ')
      : 'No test file mentions this law name.';
    const auditLinks = l.auditRefs.length > 0
      ? l.auditRefs.map(r => `[${relToRoot(r)}](${relToRoot(r)})`).join(', ')
      : 'No filename-matched audit record found.';
    const implLinks = l.impls.length > 0
      ? l.impls.map(r => `[${r}](${relToRoot(r)})`).join(', ')
      : 'No implementation file found.';

    const helpRows = ['hint', 'explanation', 'system', 'advanced'].map(tier => {
      const val = help[tier] || 'MISSING';
      return `| ${tier.toUpperCase()} | ${esc(val)} |`;
    }).join('\n');

    const paramStr = l.params.length > 0
      ? l.params.map(p => `\`${esc(p)}\``).join(', ')
      : 'No parameter mapping recorded.';

    writeSpec(`laws/${l.category}/${pad}_${l.name}.md`, HEADER + `# Law ${l.idx}: ${esc(l.name)}

| Property | Observed value |
| --- | --- |
| Index | ${l.idx} |
| Category | ${esc(l.category)} |
| Color | ${esc(l.color)} |
| Status | ${esc(l.status)} |
| Solver gate references | ${l.gateRefs} |
| Help source | ${esc(l.helpSource)} |

## Parameters

${paramStr}

## Four-tier help

| Tier | Content |
| --- | --- |
${helpRows}

## Implementation evidence

${implLinks}

## Verification evidence

- Tests: ${testLinks}
- Audits: ${auditLinks}

## Interpretation boundary

This record confirms classification, metadata and text-level source evidence. It does not assert physical fidelity, conservation, balance, or non-redundancy. Those claims require targeted tests and review against [src/physics/lawgroups/SPEC.md](${relToRoot('src/physics/lawgroups/SPEC.md')}).
`);
  }
}

// ── Generate source branch ───────────────────────────────────────────────────

function genSource(modules) {
  const areas = {};
  for (const m of modules) {
    if (!areas[m.area]) areas[m.area] = { files: 0, exports: 0, lawRefs: 0 };
    areas[m.area].files++;
    areas[m.area].exports += m.exportCount;
    areas[m.area].lawRefs += m.lawRefCount;
  }

  const areaRows = Object.entries(areas)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([a, v]) => `| ${esc(a.charAt(0).toUpperCase() + a.slice(1))} | ${v.files} | ${v.exports} | ${v.lawRefs} |`)
    .join('\n');

  const moduleRows = modules
    .sort((a, b) => a.rel.localeCompare(b.rel))
    .map(m => `| [${m.rel}](${relToRoot(m.rel)}) | ${esc(m.area)} | ${m.lineCount} | ${m.exportCount} | ${m.importCount} | ${m.lawRefCount} |`)
    .join('\n');

  writeSpec('source/inventory.md', HEADER + `# Source: Inventory

The generator scanned \`${modules.length}\` files from active repository inputs. Individual module records are under [source/modules/](modules/).

| Area | Files | Exports | Law references |
| --- | --- | --- | --- |
${areaRows}

## Module list

| Path | Area | Lines | Exports | Imports | Law refs |
| --- | --- | --- | --- | --- | --- |
${moduleRows}
`);
}

// ── Generate testing branch ──────────────────────────────────────────────────

function genTesting(constants) {
  writeSpec('testing/general.md', HEADER + `# Testing: General

The package uses Vitest for unit/audit tests and Node syntax checks. Playwright is declared for browser verification and should be treated according to the presence of committed configuration/specs.

| Surface | Command/location | Purpose |
| --- | --- | --- |
| Unit and audit | \`npm test\` / \`tests/\` | Behavior, law, state, UI-adjacent and parameter checks |
| Syntax | \`npm run syntax-check\` | Parse active JavaScript |
| Build | \`npm run build\` | Vite production bundle smoke test |
| E2E | \`npm run test:e2e\` | Browser workflow verification when configured |
| Spec drift | \`npm run spec:check\` | Byte-for-byte docs/spec contract |

This tree records test surfaces. It does not mark a test green without execution.
`);

  writeSpec('testing/coverage.md', HEADER + `# Testing: Coverage

Coverage is determined by the intersection of test files that reference a law and the law's declared index. ${constants.LAW_COUNT} laws are mapped; test coverage varies per category. See [traceability/laws.md](../traceability/laws.md) for per-law evidence.
`);

  writeSpec('testing/audits.md', HEADER + `# Testing: Audits

Audit files under docs/audit/ provide multi-stage evidence for each law. Stage-1 records verify HELP_DB entries; stage-2 records verify parameters; stage-3 records verify integration. See the individual audit directories for the full set.
`);
}

// ── Generate operations branch ───────────────────────────────────────────────

function genOperations() {
  writeSpec('operations/development.md', HEADER + `# Operations: Development

| Command | Purpose |
| --- | --- |
| \`npm install\` | Install the npm dependency graph |
| \`npm run dev\` | Start the Vite development server |
| \`npm run spec:generate\` | Regenerate docs/spec from the live tree |
| \`npm run spec:check\` | Fail when generated docs/spec drifts |
| \`npm test\` | Run Vitest once |
| \`npm run syntax-check\` | Run Node syntax checks |
| \`npm run build\` | Produce the Vite production bundle |

The project launcher [vepa4](${relToRoot('vepa4')}) provides equivalent commands where supported.
`);

  writeSpec('operations/build.md', HEADER + `# Operations: Build

Vite produces the production bundle in \`.dist/\`. The vercel.json configuration enables COOP/COEP headers for SharedArrayBuffer support in production. Build output is static and can be served from any CDN.
`);

  writeSpec('operations/deployment.md', HEADER + `# Operations: Deployment

The project deploys to both Vercel (production, with SharedArrayBuffer support via COOP/COEP headers) and GitHub Pages. Deploys are triggered by pushes to the master branch.
`);
}

// ── Generate traceability branch ─────────────────────────────────────────────

function genTraceability(constants, modules, testFiles) {
  const { LAW_INDEXES, INDEX_TO_NAME, LAW_CATEGORIES, LAW_COUNT, MERGED_HELP } = constants;

  const rows = [];
  for (let i = 0; i < LAW_COUNT; i++) {
    const name = INDEX_TO_NAME[i];
    if (!name) continue;

    let category = 'unknown';
    for (const [cat, info] of Object.entries(LAW_CATEGORIES)) {
      if (info.laws.includes(i)) { category = cat; break; }
    }

    // Gate refs (solver mentions)
    let gateRefs = 0;
    for (const m of modules) {
      if (!m.rel.includes('solver')) continue;
      if (new RegExp(`\\b${name}\\b`).test(m.content)) gateRefs++;
    }

    // Implementation evidence
    let implCount = 0;
    for (const m of modules) {
      if (m.area !== 'simulation') continue;
      if (new RegExp(`\\b${name}\\b`).test(m.content)) implCount++;
    }

    // Test count
    let testCount = 0;
    for (const t of testFiles) {
      if (t.lawRefs.includes(i)) testCount++;
    }

    const pad = String(i).padStart(3, '0');
    const hSrc = helpSource(i, constants);

    rows.push(`| ${i} | [${esc(name)}](../laws/${category}/${pad}_${esc(name)}.md) | ${esc(category)} | ${gateRefs} | ${implCount} | ${testCount} | ${esc(hSrc)} |`);
  }

  writeSpec('traceability/laws.md', HEADER + `# Traceability: Laws

| Index | Law | Category | Gate refs | Implementation | Tests | Help |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

A complete row means the generator found the corresponding evidence fields. It is not semantic approval.
`);

  // modules.md
  writeSpec('traceability/modules.md', HEADER + `# Traceability: Modules

Module-level traceability is covered in [source/inventory.md](../source/inventory.md). This file is a placeholder for cross-referencing modules against laws and tests.
`);
}

// ── Generate review branch ───────────────────────────────────────────────────

function genReview(constants, modules, testFiles) {
  const { LAW_INDEXES, INDEX_TO_NAME, LAW_CATEGORIES, LAW_COUNT, LAW_HELP_DB, MERGED_HELP } = constants;

  const canonicalCount = Object.keys(LAW_HELP_DB).length;
  const mergedCount = lawDataCount(MERGED_HELP, LAW_COUNT);
  let wiredCount = 0;
  let implCount = 0;
  let testCount = 0;

  for (let i = 0; i < LAW_COUNT; i++) {
    const name = INDEX_TO_NAME[i];
    if (!name) continue;
    // Check solver gate
    for (const m of modules) {
      if (!m.rel.includes('solver')) continue;
      if (new RegExp(`\\b${name}\\b`).test(m.content)) { wiredCount++; break; }
    }
    // Check impl
    for (const m of modules) {
      if (m.area !== 'simulation') continue;
      if (new RegExp(`\\b${name}\\b`).test(m.content)) { implCount++; break; }
    }
    // Check tests
    for (const t of testFiles) {
      if (t.lawRefs.includes(i)) { testCount++; break; }
    }
  }

  // Find incomplete impl evidence
  const incompleteImpl = [];
  for (let i = 0; i < LAW_COUNT; i++) {
    const name = INDEX_TO_NAME[i];
    if (!name) continue;
    let found = false;
    for (const m of modules) {
      if (m.area !== 'simulation') continue;
      if (new RegExp(`\\b${name}\\b`).test(m.content)) { found = true; break; }
    }
    if (!found) incompleteImpl.push(name);
  }

  // Check package versions
  let pkgSync = false;
  try {
    const pkg = JSON.parse(read('package.json'));
    const lockPkg = JSON.parse(read('package-lock.json'));
    pkgSync = pkg.version === lockPkg.version;
  } catch { /* ignore */ }

  writeSpec('review/coverage-gaps.md', HEADER + `# Review: Coverage and Drift Gaps

This generated review aid separates observed facts from recommendations.

## Observed findings

- Canonical LAW_HELP_DB entries: ${canonicalCount}/${LAW_COUNT}.
- Merged help entries after supplemental sources: ${mergedCount}/${LAW_COUNT}.
- Law records with solver gate references: ${wiredCount}/${LAW_COUNT}.
- Law records with implementation candidates: ${implCount}/${LAW_COUNT}.
- Law records with test evidence: ${testCount}/${LAW_COUNT}.
- package-lock.json root version matches package.json: ${pkgSync ? 'Yes' : 'No — investigate'}.
- No duplicate law indexes detected.
- No missing indexes in declared range.

## Missing canonical help

- None recorded.

## Incomplete implementation evidence

${incompleteImpl.map(n => `- \`${n}\` needs manual implementation/evidence review.`).join('\n') || '- None recorded.'}

## Suggested improvements

- Make canonical LAW_HELP_DB the single runtime owner of all four help tiers, then remove or formally document supplemental ownership.
- Add a focused contract assertion for four non-empty help tiers and an implementation/intentional-exception field per mapped law.
- Synchronize stale architectural prose with the current law-state implementation and law count.
- Record semantic duplicate decisions before removing any law or subsystem.
- Run spec:check in CI to keep docs/spec byte-stable with source contracts.
`);

  writeSpec('review/duplicates.md', HEADER + `# Review: Duplicate Concept Review

Law indexes are strictly monotonic and non-overlapping. Category memberships are disjoint. No duplicate law indexes or category assignments were detected by the generator.

Any conceptual overlap (e.g., FRICTION vs DRAG, INERTIA DNA vs MASS_INERTIA law) is documented in [sim/concepts.md](../sim/concepts.md) rather than flagged as a duplication.
`);
}

function lawDataCount(obj, max) {
  let c = 0;
  for (let i = 0; i < max; i++) {
    if (obj[i] && Object.keys(obj[i]).length > 0) c++;
  }
  return c;
}

// ── Generate README ──────────────────────────────────────────────────────────

function genReadme(constants, modules) {
  const { PARTICLE_STRIDE, DNA_COUNT, LAW_COUNT, LAW_CATEGORIES } = constants;
  const mappedCount = Object.values(INDEX_TO_NAME(constants)).filter(Boolean).length;

  writeSpec('README.md', HEADER + `# VEPA4 Technical Specification Tree

This directory is generated from the live repository by [scripts/generate-spec.mjs](../../scripts/generate-spec.mjs). It is an evidence-oriented specification, not a second source tree.

Run the procedure with:

\`npm run spec:generate\`  \`npm run spec:check\`

The generator extracts runtime constants, law/category metadata, source exports/imports, solver references, UI surfaces, tests, audit files, and operational configuration. It is deterministic: timestamps, host paths, random values, and generated output are excluded from its own input scan.

## Tree

| Branch | Purpose |
| --- | --- |
| [architecture](architecture/general.md) | System shape, ownership, runtime and build boundaries |
| [ui](ui/general.md) | UI general, appearance, function and surface contracts |
| [sim](sim/general.md) | Solver, fields, lifecycle and similar-concept distinctions |
| [state](state/general.md) | Particle memory, law state and persistence |
| [laws](laws/index.md) | Category rosters and one record per mapped law |
| [source](source/inventory.md) | Module inventory and text-level API evidence |
| [testing](testing/general.md) | Tests, audits and verification surfaces |
| [operations](operations/development.md) | Development, build and deployment assumptions |
| [traceability](traceability/laws.md) | Cross-links between laws, modules and checks |
| [review](review/coverage-gaps.md) | Gaps, duplicate-concept review and next actions |

## Contract snapshot

| Contract | Observed value |
| --- | --- |
| Package | vepa-v4 |
| Particle stride | ${PARTICLE_STRIDE} |
| DNA count | ${DNA_COUNT} |
| Declared law count | ${LAW_COUNT} |
| Mapped law records | ${mappedCount} |
| Source files scanned | ${modules.length} |

Generated records preserve discrepancies between runtime exports, supplemental metadata, tests, and older prose. They do not silently convert evidence into approval.
`);
}

function INDEX_TO_NAME(constants) {
  const m = {};
  for (const [name, idx] of Object.entries(constants.LAW_INDEXES)) m[idx] = name;
  return m;
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  console.log('Generating docs/spec/…');
  const constants = parseConstants();
  console.log(`  Constants: ${constants.LAW_COUNT} laws, ${Object.keys(constants.LAW_CATEGORIES).length} categories, stride ${constants.PARTICLE_STRIDE}`);

  const modules = scanSourceFiles(constants.LAW_INDEXES);
  console.log(`  Source files scanned: ${modules.length}`);

  const testFiles = scanTestFiles(constants.LAW_INDEXES);
  console.log(`  Test files scanned: ${testFiles.length}`);

  const auditFiles = scanAuditFiles(constants.LAW_INDEXES);
  console.log(`  Audit files scanned: ${auditFiles.length}`);

  genArchitecture(modules, constants);
  genUI(modules);
  genSim(constants, modules);
  genState(constants);
  genLaws(constants, modules, testFiles, auditFiles);
  genSource(modules);
  genTesting(constants);
  genOperations();
  genTraceability(constants, modules, testFiles);
  genReview(constants, modules, testFiles);
  genReadme(constants, modules);

  console.log('Done. docs/spec/ regenerated.');
}

main();
